import { faReact } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Pocky</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div>
					<h1>Desde Home</h1>
					<FontAwesomeIcon icon={faReact}/>
				</div>
			</main>
		</>
	);
}
